import { ImgCard01, ImgCard02, ImgCard03, ImgCard04 } from '@/assets/images';

export const mockCard = [
  {
    id: 1,
    name: '그린데이 좋아하시는 분 계세요?',
    author: '잼잼러',
    genres: ['얼터너티브', '락', '포크'],
    thumbnail: ImgCard01,
    totalRecruit: 5,
    totalCurrent: 3,
    recruitDeadline: '2024-06-15T23:59:59.000Z',
    member: [
      { name: '드럼', personnel: 1, total: 1 },
      { name: '보컬', personnel: 1, total: 1 },
      { name: '기타', personnel: 1, total: 2 },
    ],
  },
  {
    id: 2,
    name: '재즈 밴드 드러머 구해요!',
    author: '몽글몽글',
    genres: ['재즈', '드럼'],
    thumbnail: ImgCard02,
    totalRecruit: 4,
    totalCurrent: 2,
    recruitDeadline: '2024-06-16T23:59:59.000Z',
    member: [
      { name: '드럼', personnel: 1, total: 1 },
      { name: '보컬', personnel: 1, total: 1 },
      { name: '기타', personnel: 0, total: 1 },
    ],
  },
  {
    id: 3,
    name: '여성 보컬 모집합니다 🎤',
    author: '하이텐션',
    genres: ['팝', '보컬'],
    thumbnail: ImgCard03,
    totalRecruit: 3,
    totalCurrent: 1,
    recruitDeadline: '2024-06-17T23:59:59.000Z',
    member: [
      { name: '보컬', personnel: 1, total: 2 },
      { name: '키보드', personnel: 0, total: 1 },
    ],
  },
  {
    id: 4,
    name: '홍대에서 매주 합주하실 분!',
    author: '루프탑',
    genres: ['인디', '홍대'],
    thumbnail: ImgCard04,
    totalRecruit: 5,
    totalCurrent: 4,
    recruitDeadline: '2024-06-18T23:59:59.000Z',
    member: [
      { name: '기타', personnel: 2, total: 2 },
      { name: '베이스', personnel: 1, total: 1 },
      { name: '보컬', personnel: 1, total: 2 },
    ],
  },
  {
    id: 5,
    name: '신촌에서 매주 세션 연습해요!',
    author: '비트메이커',
    genres: ['R&B', '소울'],
    thumbnail: ImgCard04,
    totalRecruit: 4,
    totalCurrent: 3,
    recruitDeadline: '2024-06-19T23:59:59.000Z',
    member: [
      { name: '피아노', personnel: 1, total: 1 },
      { name: '드럼', personnel: 1, total: 1 },
      { name: '보컬', personnel: 1, total: 2 },
    ],
  },
  {
    id: 6,
    name: '팝 밴드로 공연 준비 중입니다!',
    author: '파워보컬',
    genres: ['팝', '댄스'],
    thumbnail: ImgCard01,
    totalRecruit: 5,
    totalCurrent: 2,
    recruitDeadline: '2024-06-20T23:59:59.000Z',
    member: [
      { name: '보컬', personnel: 1, total: 2 },
      { name: '댄서', personnel: 1, total: 2 },
    ],
  },
  {
    id: 7,
    name: '펑크락 밴드 결성 멤버 구해요!',
    author: '락앤롤',
    genres: ['펑크', '락'],
    thumbnail: ImgCard02,
    totalRecruit: 5,
    totalCurrent: 3,
    recruitDeadline: '2024-06-21T23:59:59.000Z',
    member: [
      { name: '보컬', personnel: 1, total: 1 },
      { name: '기타', personnel: 1, total: 2 },
    ],
  },
  {
    id: 8,
    name: '감성 어쿠스틱 밴드 구인',
    author: '달빛감성',
    genres: ['어쿠스틱', '포크'],
    thumbnail: ImgCard03,
    totalRecruit: 4,
    totalCurrent: 2,
    recruitDeadline: '2024-06-22T23:59:59.000Z',
    member: [
      { name: '보컬', personnel: 1, total: 1 },
      { name: '기타', personnel: 1, total: 1 },
    ],
  },
  {
    id: 9,
    name: '즉흥 재즈 팀 만들어요',
    author: 'JamKing',
    genres: ['재즈', '즉흥'],
    thumbnail: ImgCard04,
    totalRecruit: 6,
    totalCurrent: 4,
    recruitDeadline: '2024-06-23T23:59:59.000Z',
    member: [
      { name: '색소폰', personnel: 1, total: 1 },
      { name: '베이스', personnel: 1, total: 1 },
      { name: '건반', personnel: 1, total: 2 },
    ],
  },
  {
    id: 10,
    name: '드림팝 밴드 멤버 찾습니다',
    author: '몽환소리',
    genres: ['드림팝', '인디'],
    thumbnail: ImgCard03,
    totalRecruit: 4,
    totalCurrent: 2,
    recruitDeadline: '2024-06-24T23:59:59.000Z',
    member: [
      { name: '신스', personnel: 1, total: 1 },
      { name: '기타', personnel: 1, total: 2 },
    ],
  },
  {
    id: 11,
    name: '블루스 밴드 시작할 분!',
    author: '블루맨',
    genres: ['블루스'],
    thumbnail: ImgCard01,
    totalRecruit: 5,
    totalCurrent: 3,
    recruitDeadline: '2024-06-25T23:59:59.000Z',
    member: [
      { name: '보컬', personnel: 1, total: 1 },
      { name: '기타', personnel: 1, total: 2 },
      { name: '하모니카', personnel: 1, total: 1 },
    ],
  },
  {
    id: 12,
    name: '메탈 팀원 모집 🔥',
    author: '헤드뱅어',
    genres: ['메탈', '헤비'],
    thumbnail: ImgCard02,
    totalRecruit: 6,
    totalCurrent: 4,
    recruitDeadline: '2024-06-26T23:59:59.000Z',
    member: [
      { name: '기타', personnel: 2, total: 2 },
      { name: '보컬', personnel: 1, total: 1 },
      { name: '드럼', personnel: 1, total: 1 },
    ],
  },
  {
    id: 13,
    name: '7080 세대 밴드 구인',
    author: '회상',
    genres: ['트로트', '7080'],
    thumbnail: ImgCard03,
    totalRecruit: 4,
    totalCurrent: 3,
    recruitDeadline: '2024-06-27T23:59:59.000Z',
    member: [
      { name: '건반', personnel: 1, total: 1 },
      { name: '보컬', personnel: 1, total: 2 },
    ],
  },
  {
    id: 14,
    name: 'EDM 콜라보 팀',
    author: 'DJSun',
    genres: ['EDM', '일렉트로닉'],
    thumbnail: ImgCard04,
    totalRecruit: 3,
    totalCurrent: 2,
    recruitDeadline: '2024-06-28T23:59:59.000Z',
    member: [
      { name: 'DJ', personnel: 1, total: 1 },
      { name: '보컬', personnel: 1, total: 2 },
    ],
  },
  {
    id: 15,
    name: '락페 준비할 밴드모집',
    author: '페스티벌러',
    genres: ['락', '페스티벌'],
    thumbnail: ImgCard03,
    totalRecruit: 6,
    totalCurrent: 5,
    recruitDeadline: '2024-06-29T23:59:59.000Z',
    member: [
      { name: '보컬', personnel: 1, total: 1 },
      { name: '기타', personnel: 2, total: 2 },
      { name: '드럼', personnel: 1, total: 1 },
      { name: '베이스', personnel: 1, total: 1 },
    ],
  },
  {
    id: 16,
    name: '홍대에서 펑크락 밴드 구인합니다!',
    author: '펑커',
    genres: ['펑크', '홍대', '락'],
    thumbnail: ImgCard01,
    totalRecruit: 5,
    totalCurrent: 3,
    recruitDeadline: '2024-06-30T23:59:59.000Z',
    member: [
      { name: '보컬', personnel: 1, total: 1 },
      { name: '기타', personnel: 1, total: 2 },
      { name: '드럼', personnel: 1, total: 1 },
    ],
  },
  {
    id: 17,
    name: '피아노와 함께 재즈하실 분',
    author: '재즈피아니스트',
    genres: ['재즈', '피아노'],
    thumbnail: ImgCard02,
    totalRecruit: 3,
    totalCurrent: 2,
    recruitDeadline: '2024-07-01T23:59:59.000Z',
    member: [
      { name: '피아노', personnel: 1, total: 1 },
      { name: '보컬', personnel: 1, total: 1 },
    ],
  },
  {
    id: 18,
    name: '보컬만 구해요! 락밴드입니다',
    author: '강철심장',
    genres: ['락', '보컬'],
    thumbnail: ImgCard03,
    totalRecruit: 4,
    totalCurrent: 3,
    recruitDeadline: '2024-07-02T23:59:59.000Z',
    member: [
      { name: '보컬', personnel: 0, total: 1 },
      { name: '기타', personnel: 2, total: 2 },
      { name: '드럼', personnel: 1, total: 1 },
    ],
  },
  {
    id: 19,
    name: '인디팝 팀으로 활동하실 분',
    author: '소소한행복',
    genres: ['인디', '팝'],
    thumbnail: ImgCard04,
    totalRecruit: 4,
    totalCurrent: 2,
    recruitDeadline: '2024-07-03T23:59:59.000Z',
    member: [
      { name: '보컬', personnel: 1, total: 1 },
      { name: '신스', personnel: 1, total: 1 },
    ],
  },
  {
    id: 20,
    name: '어쿠스틱 듀오 모집해요 🎶',
    author: '듀엣러버',
    genres: ['어쿠스틱', '포크'],
    thumbnail: ImgCard04,
    totalRecruit: 2,
    totalCurrent: 1,
    recruitDeadline: '2024-07-04T23:59:59.000Z',
    member: [
      { name: '보컬', personnel: 1, total: 1 },
      { name: '기타', personnel: 0, total: 1 },
    ],
  },
  {
    id: 21,
    name: '랩 & 힙합 콜라보 멤버 구해요',
    author: '랩갓',
    genres: ['랩', '힙합'],
    thumbnail: ImgCard01,
    totalRecruit: 3,
    totalCurrent: 2,
    recruitDeadline: '2024-07-05T23:59:59.000Z',
    member: [
      { name: '래퍼', personnel: 1, total: 2 },
      { name: '비트메이커', personnel: 1, total: 1 },
    ],
  },
  {
    id: 22,
    name: '하드락 사운드 좋아하시는 분',
    author: '기타히어로',
    genres: ['하드락', '락'],
    thumbnail: ImgCard02,
    totalRecruit: 5,
    totalCurrent: 3,
    recruitDeadline: '2024-07-06T23:59:59.000Z',
    member: [
      { name: '기타', personnel: 2, total: 2 },
      { name: '드럼', personnel: 1, total: 1 },
      { name: '보컬', personnel: 0, total: 1 },
    ],
  },
  {
    id: 23,
    name: '플루트와 함께하는 클래식 밴드',
    author: '클래식러',
    genres: ['클래식', '플루트'],
    thumbnail: ImgCard03,
    totalRecruit: 4,
    totalCurrent: 2,
    recruitDeadline: '2024-07-07T23:59:59.000Z',
    member: [
      { name: '플루트', personnel: 1, total: 1 },
      { name: '피아노', personnel: 1, total: 1 },
    ],
  },
  {
    id: 24,
    name: '감성적인 팝팀 찾습니다',
    author: '밤하늘',
    genres: ['팝', '발라드'],
    thumbnail: ImgCard04,
    totalRecruit: 3,
    totalCurrent: 2,
    recruitDeadline: '2024-07-08T23:59:59.000Z',
    member: [
      { name: '보컬', personnel: 1, total: 2 },
      { name: '피아노', personnel: 1, total: 1 },
    ],
  },
  {
    id: 25,
    name: '브라스 밴드 만들어봐요 🎺',
    author: '골든혼',
    genres: ['브라스', '재즈'],
    thumbnail: ImgCard04,
    totalRecruit: 6,
    totalCurrent: 4,
    recruitDeadline: '2024-07-09T23:59:59.000Z',
    member: [
      { name: '트럼펫', personnel: 1, total: 2 },
      { name: '색소폰', personnel: 1, total: 2 },
      { name: '튜바', personnel: 1, total: 2 },
    ],
  },
  {
    id: 26,
    name: '몽환적인 사운드 팀 만들어요',
    author: '드림스케이프',
    genres: ['드림팝', '신스팝'],
    thumbnail: ImgCard01,
    totalRecruit: 4,
    totalCurrent: 2,
    recruitDeadline: '2024-07-10T23:59:59.000Z',
    member: [
      { name: '보컬', personnel: 1, total: 1 },
      { name: '신스', personnel: 1, total: 2 },
    ],
  },
  {
    id: 27,
    name: '힙합/R&B 듀오 찾습니다 🎤',
    author: '소울메이트',
    genres: ['힙합', 'R&B'],
    thumbnail: ImgCard02,
    totalRecruit: 2,
    totalCurrent: 1,
    recruitDeadline: '2024-07-11T23:59:59.000Z',
    member: [
      { name: '보컬', personnel: 0, total: 1 },
      { name: '래퍼', personnel: 1, total: 1 },
    ],
  },
  {
    id: 28,
    name: '신나는 라틴밴드 함께해요!',
    author: '살사킹',
    genres: ['라틴', '살사'],
    thumbnail: ImgCard03,
    totalRecruit: 5,
    totalCurrent: 3,
    recruitDeadline: '2024-07-12T23:59:59.000Z',
    member: [
      { name: '퍼커션', personnel: 1, total: 2 },
      { name: '건반', personnel: 1, total: 1 },
      { name: '보컬', personnel: 1, total: 2 },
    ],
  },
  {
    id: 29,
    name: 'K-POP 댄스팀 구성원 모집',
    author: 'K스타일',
    genres: ['K-POP', '댄스'],
    thumbnail: ImgCard04,
    totalRecruit: 6,
    totalCurrent: 4,
    recruitDeadline: '2024-07-13T23:59:59.000Z',
    member: [
      { name: '댄서', personnel: 3, total: 3 },
      { name: '보컬', personnel: 1, total: 2 },
    ],
  },
  {
    id: 30,
    name: '합주할 기타리스트 찾습니다',
    author: '스트링러버',
    genres: ['기타', '인디', '모던락'],
    thumbnail: ImgCard04,
    totalRecruit: 4,
    totalCurrent: 3,
    recruitDeadline: '2024-07-14T23:59:59.000Z',
    member: [
      { name: '기타', personnel: 1, total: 2 },
      { name: '보컬', personnel: 1, total: 1 },
      { name: '베이스', personnel: 1, total: 1 },
    ],
  },
  {
    id: 31,
    name: '그린데이 좋아하시는 분 계세요?',
    author: '잼잼러',
    genres: ['얼터너티브', '락', '포크'],
    thumbnail: ImgCard01,
    totalRecruit: 5,
    totalCurrent: 3,
    recruitDeadline: '2024-06-15T23:59:59.000Z',
    member: [
      { name: '드럼', personnel: 1, total: 1 },
      { name: '보컬', personnel: 1, total: 1 },
      { name: '기타', personnel: 1, total: 2 },
    ],
  },
  {
    id: 32,
    name: '재즈 밴드 드러머 구해요!',
    author: '몽글몽글',
    genres: ['재즈', '드럼'],
    thumbnail: ImgCard02,
    totalRecruit: 4,
    totalCurrent: 2,
    recruitDeadline: '2024-06-16T23:59:59.000Z',
    member: [
      { name: '드럼', personnel: 1, total: 1 },
      { name: '보컬', personnel: 1, total: 1 },
      { name: '기타', personnel: 0, total: 1 },
    ],
  },
  {
    id: 33,
    name: '여성 보컬 모집합니다 🎤',
    author: '하이텐션',
    genres: ['팝', '보컬'],
    thumbnail: ImgCard03,
    totalRecruit: 3,
    totalCurrent: 1,
    recruitDeadline: '2024-06-17T23:59:59.000Z',
    member: [
      { name: '보컬', personnel: 1, total: 2 },
      { name: '키보드', personnel: 0, total: 1 },
    ],
  },
  {
    id: 34,
    name: '홍대에서 매주 합주하실 분!',
    author: '루프탑',
    genres: ['인디', '홍대'],
    thumbnail: ImgCard04,
    totalRecruit: 5,
    totalCurrent: 4,
    recruitDeadline: '2024-06-18T23:59:59.000Z',
    member: [
      { name: '기타', personnel: 2, total: 2 },
      { name: '베이스', personnel: 1, total: 1 },
      { name: '보컬', personnel: 1, total: 2 },
    ],
  },
  {
    id: 35,
    name: '신촌에서 매주 세션 연습해요!',
    author: '비트메이커',
    genres: ['R&B', '소울'],
    thumbnail: ImgCard04,
    totalRecruit: 4,
    totalCurrent: 3,
    recruitDeadline: '2024-06-19T23:59:59.000Z',
    member: [
      { name: '피아노', personnel: 1, total: 1 },
      { name: '드럼', personnel: 1, total: 1 },
      { name: '보컬', personnel: 1, total: 2 },
    ],
  },
  {
    id: 36,
    name: '팝 밴드로 공연 준비 중입니다!',
    author: '파워보컬',
    genres: ['팝', '댄스'],
    thumbnail: ImgCard01,
    totalRecruit: 5,
    totalCurrent: 2,
    recruitDeadline: '2024-06-20T23:59:59.000Z',
    member: [
      { name: '보컬', personnel: 1, total: 2 },
      { name: '댄서', personnel: 1, total: 2 },
    ],
  },
  {
    id: 37,
    name: '펑크락 밴드 결성 멤버 구해요!',
    author: '락앤롤',
    genres: ['펑크', '락'],
    thumbnail: ImgCard02,
    totalRecruit: 5,
    totalCurrent: 3,
    recruitDeadline: '2024-06-21T23:59:59.000Z',
    member: [
      { name: '보컬', personnel: 1, total: 1 },
      { name: '기타', personnel: 1, total: 2 },
    ],
  },
  {
    id: 38,
    name: '감성 어쿠스틱 밴드 구인',
    author: '달빛감성',
    genres: ['어쿠스틱', '포크'],
    thumbnail: ImgCard03,
    totalRecruit: 4,
    totalCurrent: 2,
    recruitDeadline: '2024-06-22T23:59:59.000Z',
    member: [
      { name: '보컬', personnel: 1, total: 1 },
      { name: '기타', personnel: 1, total: 1 },
    ],
  },
  {
    id: 39,
    name: '즉흥 재즈 팀 만들어요',
    author: 'JamKing',
    genres: ['재즈', '즉흥'],
    thumbnail: ImgCard04,
    totalRecruit: 6,
    totalCurrent: 4,
    recruitDeadline: '2024-06-23T23:59:59.000Z',
    member: [
      { name: '색소폰', personnel: 1, total: 1 },
      { name: '베이스', personnel: 1, total: 1 },
      { name: '건반', personnel: 1, total: 2 },
    ],
  },
  {
    id: 40,
    name: '드림팝 밴드 멤버 찾습니다',
    author: '몽환소리',
    genres: ['드림팝', '인디'],
    thumbnail: ImgCard03,
    totalRecruit: 4,
    totalCurrent: 2,
    recruitDeadline: '2024-06-24T23:59:59.000Z',
    member: [
      { name: '신스', personnel: 1, total: 1 },
      { name: '기타', personnel: 1, total: 2 },
    ],
  },
];
